services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  rabbitmq:
    image: "docker.io/library/rabbitmq:4.2-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    expose:
      - "5672"
      - "15672"
    volumes:
      - type: "volume"
        target: "/var/lib/rabbitmq"
        source: "dormitory.apphost-00cc8309c5-rabbitmq-data"
        read_only: false
    networks:
      - "aspire"
  identity-api:
    image: "${IDENTITY_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${IDENTITY_API_PORT}"
      ConnectionStrings__identitydb: "${IDENTITYDB}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "identity-api"
    expose:
      - "${IDENTITY_API_PORT}"
    networks:
      - "aspire"
  profile-api:
    image: "${PROFILE_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${PROFILE_API_PORT}"
      ConnectionStrings__profiledb: "${PROFILEDB}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "profile-api"
    expose:
      - "${PROFILE_API_PORT}"
    networks:
      - "aspire"
  room-api:
    image: "${ROOM_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${ROOM_API_PORT}"
      ConnectionStrings__roomdb: "${ROOMDB}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "room-api"
    expose:
      - "${ROOM_API_PORT}"
    networks:
      - "aspire"
  booking-api:
    image: "${BOOKING_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${BOOKING_API_PORT}"
      ConnectionStrings__bookingdb: "${BOOKINGDB}"
      ROOM_API_HTTP: "http://room-api:${ROOM_API_PORT}"
      services__room-api__http__0: "http://room-api:${ROOM_API_PORT}"
      ROOM_API_HTTPS: "https://room-api:${ROOM_API_PORT}"
      ConnectionStrings__rabbitmq: "amqp://guest:${RABBITMQ_PASSWORD}@rabbitmq:5672"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      RABBITMQ_URI: "amqp://guest:${RABBITMQ_PASSWORD}@rabbitmq:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "booking-api"
    expose:
      - "${BOOKING_API_PORT}"
    depends_on:
      room-api:
        condition: "service_started"
    networks:
      - "aspire"
  community-api:
    image: "${COMMUNITY_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${COMMUNITY_API_PORT}"
      ConnectionStrings__communitydb: "${COMMUNITYDB}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "community-api"
    expose:
      - "${COMMUNITY_API_PORT}"
    networks:
      - "aspire"
  incident-api:
    image: "${INCIDENT_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${INCIDENT_API_PORT}"
      ConnectionStrings__incidentdb: "${INCIDENTDB}"
      ConnectionStrings__rabbitmq: "amqp://guest:${RABBITMQ_PASSWORD}@rabbitmq:5672"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      RABBITMQ_URI: "amqp://guest:${RABBITMQ_PASSWORD}@rabbitmq:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "incident-api"
    expose:
      - "${INCIDENT_API_PORT}"
    networks:
      - "aspire"
  gateway-api:
    image: "${GATEWAY_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${GATEWAY_API_PORT}"
      IDENTITY_API_HTTP: "http://identity-api:${IDENTITY_API_PORT}"
      services__identity-api__http__0: "http://identity-api:${IDENTITY_API_PORT}"
      IDENTITY_API_HTTPS: "https://identity-api:${IDENTITY_API_PORT}"
      ROOM_API_HTTP: "http://room-api:${ROOM_API_PORT}"
      services__room-api__http__0: "http://room-api:${ROOM_API_PORT}"
      ROOM_API_HTTPS: "https://room-api:${ROOM_API_PORT}"
      PROFILE_API_HTTP: "http://profile-api:${PROFILE_API_PORT}"
      services__profile-api__http__0: "http://profile-api:${PROFILE_API_PORT}"
      PROFILE_API_HTTPS: "https://profile-api:${PROFILE_API_PORT}"
      BOOKING_API_HTTP: "http://booking-api:${BOOKING_API_PORT}"
      services__booking-api__http__0: "http://booking-api:${BOOKING_API_PORT}"
      BOOKING_API_HTTPS: "https://booking-api:${BOOKING_API_PORT}"
      COMMUNITY_API_HTTP: "http://community-api:${COMMUNITY_API_PORT}"
      services__community-api__http__0: "http://community-api:${COMMUNITY_API_PORT}"
      COMMUNITY_API_HTTPS: "https://community-api:${COMMUNITY_API_PORT}"
      INCIDENT_API_HTTP: "http://incident-api:${INCIDENT_API_PORT}"
      services__incident-api__http__0: "http://incident-api:${INCIDENT_API_PORT}"
      INCIDENT_API_HTTPS: "https://incident-api:${INCIDENT_API_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "gateway-api"
    ports:
      - "${GATEWAY_API_PORT}"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  dormitory.apphost-00cc8309c5-rabbitmq-data:
    driver: "local"
