// <auto-generated />
using System;
using Billing.API.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Billing.API.Infrastructure.Database.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260529013848_AddInvoiceRoomLocationAndCanceledStatus")]
    partial class AddInvoiceRoomLocationAndCanceledStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Billing.API.Domain.Entities.ContractTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.HasIndex("IsActive", "EffectiveFrom");

                    b.ToTable("ContractTemplates", (string)null);
                });

            modelBuilder.Entity("Billing.API.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("BillingMonth")
                        .HasColumnType("smallint");

                    b.Property<int>("BillingYear")
                        .HasColumnType("integer");

                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ContractTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ElectricityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ElectricityNewIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ElectricityOldIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ElectricityTierSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ElectricityUsage")
                        .HasColumnType("integer");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SurchargeTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WaterAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("WaterNewIndex")
                        .HasColumnType("integer");

                    b.Property<int>("WaterOldIndex")
                        .HasColumnType("integer");

                    b.Property<string>("WaterTierSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("WaterUsage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractTemplateId");

                    b.HasIndex("RoomId", "BillingYear", "BillingMonth")
                        .IsUnique();

                    b.HasIndex("Status", "BillingYear", "BillingMonth");

                    b.HasIndex("RoomId", "BillingYear", "BillingMonth", "CreatedAt")
                        .IsDescending(false, true, true, true);

                    b.HasIndex("BuildingCode", "Floor", "BillingYear", "BillingMonth", "Status");

                    b.ToTable("Invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_ElectricityIndex", "\"ElectricityNewIndex\" >= \"ElectricityOldIndex\"");

                            t.HasCheckConstraint("CK_Invoices_Floor", "\"Floor\" IS NULL OR \"Floor\" > 0");

                            t.HasCheckConstraint("CK_Invoices_WaterIndex", "\"WaterNewIndex\" >= \"WaterOldIndex\"");
                        });
                });

            modelBuilder.Entity("Billing.API.Domain.Entities.ServicePriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal>("FromUsage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("RoomCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ToUsage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceType", "EffectiveFrom", "FromUsage")
                        .IsUnique()
                        .HasDatabaseName("IX_ServicePriceTiers_UQ_GlobalCapacity")
                        .HasFilter("\"RoomCapacity\" IS NULL");

                    b.HasIndex("ServiceType", "EffectiveFrom", "RoomCapacity", "FromUsage")
                        .IsUnique()
                        .HasDatabaseName("IX_ServicePriceTiers_UQ_RoomCapacity")
                        .HasFilter("\"RoomCapacity\" IS NOT NULL");

                    b.HasIndex("ServiceType", "IsActive", "EffectiveFrom", "RoomCapacity", "FromUsage");

                    b.ToTable("ServicePriceTiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServicePriceTiers_RoomCapacity", "\"RoomCapacity\" IS NULL OR \"RoomCapacity\" > 0");
                        });
                });

            modelBuilder.Entity("Billing.API.Domain.Entities.Surcharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Surcharges", null, t =>
                        {
                            t.HasCheckConstraint("CK_Surcharges_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Billing.API.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Billing.API.Domain.Entities.ContractTemplate", "ContractTemplate")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContractTemplate");
                });

            modelBuilder.Entity("Billing.API.Domain.Entities.Surcharge", b =>
                {
                    b.HasOne("Billing.API.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Surcharges")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Billing.API.Domain.Entities.ContractTemplate", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Billing.API.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Surcharges");
                });
#pragma warning restore 612, 618
        }
    }
}
